name: data_analysis
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.2.25=haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - openssl=1.1.1w=h2bbff1b_0
  - pip=25.1=pyhc872135_2
  - python=3.10.0=h96c0403_3
  - setuptools=78.1.1=py310haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - tk=8.6.14=h5e9d12e_1
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.42.34433=h84bc874_10
  - vs2015_runtime=14.42.34433=he0c19fb_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.2.13=h500123d_2
  - pip:
      - appdirs==1.4.4
      - asttokens==3.0.0
      - attrs==25.4.0
      - backoff==2.2.1
      - cachetools==5.5.2
      - catboost==1.2.8
      - certifi==2025.10.5
      - charset-normalizer==3.4.3
      - choreographer==1.2.1
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - dateparser==1.2.2
      - debugpy==1.8.17
      - decisiontree==3.4.3
      - decorator==5.2.1
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - fonttools==4.58.0
      - graphviz==0.21
      - idna==3.10
      - iniconfig==2.3.0
      - ipykernel==7.1.0
      - ipython==8.37.0
      - jedi==0.19.2
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - kaleido==1.2.0
      - kiwisolver==1.4.8
      - lightgbm==4.6.0
      - logistro==2.0.1
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - narwhals==1.40.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - numpy==2.2.6
      - openpyxl==3.1.5
      - orjson==3.11.4
      - packaging==25.0
      - pandas==2.3.1
      - parso==0.8.5
      - pillow==11.3.0
      - platformdirs==4.5.0
      - plotly==6.1.1
      - pluggy==1.6.0
      - prompt-toolkit==3.0.52
      - psutil==7.1.2
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.2.3
      - pytest==9.0.1
      - pytest-timeout==2.4.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyzmq==27.1.0
      - referencing==0.37.0
      - regex==2024.11.6
      - requests==2.32.4
      - rpds-py==0.28.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - shelved-cache==0.3.1
      - simplejson==3.20.2
      - six==1.17.0
      - stack-data==0.6.3
      - tabulate==0.8.10
      - threadpoolctl==3.6.0
      - tomli==2.3.0
      - tornado==6.5.2
      - traitlets==5.14.3
      - typing-extensions==4.14.1
      - tzdata==2025.2
      - tzlocal==5.3.1
      - urllib3==2.5.0
      - wbdata==1.0.0
      - wcwidth==0.2.14
      - xgboost==3.1.1
prefix: C:\Users\My-PC\miniconda3\envs\data_analysis
